// Code generated by MockGen. DO NOT EDIT.
// Source: internal/excel/ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/devpablocristo/monorepo/projects/qh/internal/excel/handler/dto"
	domain "github.com/devpablocristo/monorepo/projects/qh/internal/excel/usecases/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockPerson_2Repository is a mock of Person_2Repository interface.
type MockPerson_2Repository struct {
	ctrl     *gomock.Controller
	recorder *MockPerson_2RepositoryMockRecorder
}

// MockPerson_2RepositoryMockRecorder is the mock recorder for MockPerson_2Repository.
type MockPerson_2RepositoryMockRecorder struct {
	mock *MockPerson_2Repository
}

// NewMockPerson_2Repository creates a new mock instance.
func NewMockPerson_2Repository(ctrl *gomock.Controller) *MockPerson_2Repository {
	mock := &MockPerson_2Repository{ctrl: ctrl}
	mock.recorder = &MockPerson_2RepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPerson_2Repository) EXPECT() *MockPerson_2RepositoryMockRecorder {
	return m.recorder
}

// SavePerson mocks base method.
func (m *MockPerson_2Repository) SavePerson(arg0 context.Context, arg1 []domain.Person_2) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePerson", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePerson indicates an expected call of SavePerson.
func (mr *MockPerson_2RepositoryMockRecorder) SavePerson(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePerson", reflect.TypeOf((*MockPerson_2Repository)(nil).SavePerson), arg0, arg1)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// SaveOrder mocks base method.
func (m *MockOrderRepository) SaveOrder(arg0 context.Context, arg1 []domain.Order) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderRepositoryMockRecorder) SaveOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderRepository)(nil).SaveOrder), arg0, arg1)
}

// MockUseCases is a mock of UseCases interface.
type MockUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockUseCasesMockRecorder
}

// MockUseCasesMockRecorder is the mock recorder for MockUseCases.
type MockUseCasesMockRecorder struct {
	mock *MockUseCases
}

// NewMockUseCases creates a new mock instance.
func NewMockUseCases(ctrl *gomock.Controller) *MockUseCases {
	mock := &MockUseCases{ctrl: ctrl}
	mock.recorder = &MockUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCases) EXPECT() *MockUseCasesMockRecorder {
	return m.recorder
}

// ProccesOrder mocks base method.
func (m *MockUseCases) ProccesOrder(arg0 context.Context, arg1 []dto.OrderDto) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProccesOrder", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProccesOrder indicates an expected call of ProccesOrder.
func (mr *MockUseCasesMockRecorder) ProccesOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProccesOrder", reflect.TypeOf((*MockUseCases)(nil).ProccesOrder), arg0, arg1)
}

// ProccesPerson mocks base method.
func (m *MockUseCases) ProccesPerson(arg0 context.Context, arg1 []dto.ExcelPerson) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProccesPerson", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProccesPerson indicates an expected call of ProccesPerson.
func (mr *MockUseCasesMockRecorder) ProccesPerson(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProccesPerson", reflect.TypeOf((*MockUseCases)(nil).ProccesPerson), arg0, arg1)
}
