// Code generated by MockGen. DO NOT EDIT.
// Source: internal/project/ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/devpablocristo/monorepo/projects/qh/internal/project/handler/dto"
	domain "github.com/devpablocristo/monorepo/projects/qh/internal/project/usecases/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUseCases is a mock of UseCases interface.
type MockUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockUseCasesMockRecorder
}

// MockUseCasesMockRecorder is the mock recorder for MockUseCases.
type MockUseCasesMockRecorder struct {
	mock *MockUseCases
}

// NewMockUseCases creates a new mock instance.
func NewMockUseCases(ctrl *gomock.Controller) *MockUseCases {
	mock := &MockUseCases{ctrl: ctrl}
	mock.recorder = &MockUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCases) EXPECT() *MockUseCasesMockRecorder {
	return m.recorder
}

// ProcessFullProjects mocks base method.
func (m *MockUseCases) ProcessFullProjects(arg0 context.Context, arg1 []dto.FullProjectDTO) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessFullProjects", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessFullProjects indicates an expected call of ProcessFullProjects.
func (mr *MockUseCasesMockRecorder) ProcessFullProjects(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessFullProjects", reflect.TypeOf((*MockUseCases)(nil).ProcessFullProjects), arg0, arg1)
}

// MockFullProjectsRepo is a mock of FullProjectsRepo interface.
type MockFullProjectsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFullProjectsRepoMockRecorder
}

// MockFullProjectsRepoMockRecorder is the mock recorder for MockFullProjectsRepo.
type MockFullProjectsRepoMockRecorder struct {
	mock *MockFullProjectsRepo
}

// NewMockFullProjectsRepo creates a new mock instance.
func NewMockFullProjectsRepo(ctrl *gomock.Controller) *MockFullProjectsRepo {
	mock := &MockFullProjectsRepo{ctrl: ctrl}
	mock.recorder = &MockFullProjectsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFullProjectsRepo) EXPECT() *MockFullProjectsRepoMockRecorder {
	return m.recorder
}

// SaveFullProject mocks base method.
func (m *MockFullProjectsRepo) SaveFullProject(arg0 context.Context, arg1 []domain.FullProject) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFullProject", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFullProject indicates an expected call of SaveFullProject.
func (mr *MockFullProjectsRepoMockRecorder) SaveFullProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFullProject", reflect.TypeOf((*MockFullProjectsRepo)(nil).SaveFullProject), arg0, arg1)
}
